# Generated by Django 5.2.3 on 2025-07-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
