# Generated by Django 5.2.3 on 2025-07-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
