# Generated by Django 5.2.3 on 2025-07-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_applied_at_application_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='applied_at',
        ),
    ]
