# Generated by Django 5.2.2 on 2025-07-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='job_seeker', max_length=20),
        ),
    ]
