# Generated by Django 5.2.3 on 2025-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
