# Generated by Django 5.2.3 on 2025-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_job_posted_by_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Font Awesome class, e.g., 'fas fa-code'", max_length=50)),
                ('color', models.CharField(help_text="Bootstrap text color class, e.g., 'text-primary'", max_length=20)),
                ('job_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
            },
        ),
    ]
