# Generated by Django 5.2.3 on 2025-07-10 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_jobalert_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_job_view',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
