# Generated by Django 5.2.3 on 2025-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_profile_last_job_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email_sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
